import type { Metadata } from 'next'
import { crimsonText } from './fonts';
import './globals.css'
import '@fontsource/crimson-text';
import Navbar from './components/Navbar'
import Footer from './components/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={crimsonText.className}>
          <Navbar/>
          {children}
          <Footer/>   
      </body>
    </html>
  )
}
